version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flashsale-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: flashsale-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
  #      - flashsale-service
  #      - inventory-service

  #
  #  flashsale-service:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #      args:
  #        MODULE_NAME: flashsale-service
  #    container_name: flashsale-service
  #    ports:
  #      - "8082:8082"
  #    environment:
  #      - DB_HOST=postgres
  #      - REDIS_HOST=redis
  #    depends_on:
  #      postgres:
  #        condition: service_healthy
  #      redis:
  #        condition: service_healthy
  #
  #  inventory-service:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #      args:
  #        MODULE_NAME: inventory-service
  #    container_name: inventory-service
  #    ports:
  #      - "8083:8083"
  #    environment:
  #      - DB_HOST=postgres
  #      - REDIS_HOST=redis
  #    depends_on:
  #      postgres:
  #        condition: service_healthy
  #      redis:
  #        condition: service_healthy

volumes:
  postgres_data:
